<?php

namespace DisBike\BikeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DistanceIncreaseEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DistanceIncreaseEventRepository extends EntityRepository
{
}
